version: '3.1'

services:
  db:
    image: postgres:15
    restart: always
    container_name: maumlab-survey-test-db
    env_file:
      - ./.env
    ports:
      - 5433:5432
    volumes:
      - ./database:/var/lib/postgresql/data
