export const enum CommonErrorCodeEnum {
  INVALID_PARAM = -1,
  UNAUTHORIZED = -2,
  NOT_ENABLED_FEATURE = -3,
  BLOCKED = -4,
  FORBIDDEN_REQUEST = -5,
  INTERNAL_SERVER = -6,
  UNDER_INSPECTION = -7,
}
